name: Docker Release

on:
  # This can be used to automatically publish releases
  release:
    types: [published]
  # This can be used to allow manually triggering nightlies from the web interface
  workflow_dispatch:

jobs:
  docker:
    if: github.repository_owner == 'McPringle'
    runs-on: ubuntu-latest
    name: Docker Release

    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: mcpringle/komunumo:${{ github.event.release.tag_name }}
          platforms: linux/amd64
#          platforms: linux/amd64,linux/arm64
